BEGIN;
UPDATE cadetes SET email = 'tp.cacerescoc@fab.mil.br' WHERE id = '24-034';
UPDATE cadetes SET email = 'tp.araujopham@fab.mil.br' WHERE id = '24-035';
UPDATE cadetes SET email = 'tp.pamellapcac@fab.mil.br' WHERE id = '24-056';
UPDATE cadetes SET email = 'tp.baracalhbgrb@fab.mil.br' WHERE id = '24-098';
UPDATE cadetes SET email = 'tp.simoeslsfg@fab.mil.br' WHERE id = '24-119';
UPDATE cadetes SET email = 'tp.tiburciomrft@fab.mil.br' WHERE id = '24-202';
UPDATE cadetes SET email = 'tp.lourencopll@fab.mil.br' WHERE id = '24-277';
UPDATE cadetes SET email = 'tp.conceicaolgcs@fab.mil.br' WHERE id = '24-278';
UPDATE cadetes SET email = 'tp.olegarionaos@fab.mil.br' WHERE id = '24-339';
UPDATE cadetes SET email = 'tp.pedrorenoprp@fab.mil.br' WHERE id = '25-001';
UPDATE cadetes SET email = 'tp.horacionohcf@fab.mil.br' WHERE id = '25-038';
UPDATE cadetes SET email = 'tp.lavinialvb@fab.mil.br' WHERE id = '25-044';
UPDATE cadetes SET email = 'tp.andremouraalmm@fab.mil.br' WHERE id = '25-047';
UPDATE cadetes SET email = 'tp.joaojpf@fab.mil.br' WHERE id = '25-060';
UPDATE cadetes SET email = 'tp.luizfelipelfbo@fab.mil.br' WHERE id = '25-073';
UPDATE cadetes SET email = 'tp.viniciusvmc@fab.mil.br' WHERE id = '25-082';
UPDATE cadetes SET email = 'tp.vizcainojjvp@fab.mil.br' WHERE id = '25-401';
UPDATE cadetes SET email = 'tp.maguinajamb@fab.mil.br' WHERE id = '25-402';
UPDATE cadetes SET email = 'tp.uchoacvsu@fab.mil.br' WHERE id = '26-007';
UPDATE cadetes SET email = 'tp.estevaojeof@fab.mil.br' WHERE id = '26-008';
COMMIT;
