BEGIN;
UPDATE cadetes SET email = 'tp.gregoriorgfr@fab.mil.br' WHERE id = '24-010';
UPDATE cadetes SET email = 'tp.juliajfr@fab.mil.br' WHERE id = '23-007';
UPDATE cadetes SET email = 'tp.custodiomac@fab.mil.br' WHERE id = '23-105';
UPDATE cadetes SET email = 'tp.alefetao@fab.mil.br' WHERE id = '23-106';
UPDATE cadetes SET email = 'tp.pecanhaldlp@fab.mil.br' WHERE id = '23-120';
UPDATE cadetes SET email = 'tp.magalhaesdsvm@fab.mil.br' WHERE id = '23-122';
UPDATE cadetes SET email = 'tp.viniciusalvesvoa@fab.mil.br' WHERE id = '23-141';
UPDATE cadetes SET email = 'tp.viniciusdivinovsad@fab.mil.br' WHERE id = '23-159';
UPDATE cadetes SET email = 'tp.aragaocaa@fab.mil.br' WHERE id = '23-206';
UPDATE cadetes SET email = 'tp.juliabrandaojbmt@fab.mil.br' WHERE id = '23-212';
UPDATE cadetes SET email = 'tp.juliasousajts@fab.mil.br' WHERE id = '23-213';
UPDATE cadetes SET email = 'tp.annaleticiaaldm@fab.mil.br' WHERE id = '23-223';
UPDATE cadetes SET email = 'tp.andreoliveiraalos@fab.mil.br' WHERE id = '23-229';
UPDATE cadetes SET email = 'tp.thainatcmb@fab.mil.br' WHERE id = '23-235';
UPDATE cadetes SET email = 'tp.esthefanyebc@fab.mil.br' WHERE id = '23-238';
UPDATE cadetes SET email = 'tp.josefelipejfs@fab.mil.br' WHERE id = '23-241';
UPDATE cadetes SET email = 'tp.laislbsc@fab.mil.br' WHERE id = '23-245';
UPDATE cadetes SET email = 'tp.venanciojvvgm@fab.mil.br' WHERE id = '23-309';
UPDATE cadetes SET email = 'tp.magalhaesresendewmvr@fab.mil.br' WHERE id = '23-316';
UPDATE cadetes SET email = 'tp.jessicacallegarijcso@fab.mil.br' WHERE id = '24-025';
COMMIT;
